### ISSUE TITLE
About 'DDI_DB_pos.csv'、'DDI_DB_neg.csv'、'DDI_DB_all_v1.csv'

### ISSUE THREAD

**Issue by ren-364** [Jialun-WU/MEGACare#2]
Hi there, This is excellent work, and thanks a lot for your open-source code.
I ran into a problem regarding the drug-drug side effects, and I need to figure out how this data is generated and some illustrations about the schema of this file.Could you please tell me how these files were generated or provide them directly?
Thank you very much.

**Comment by Forwhyy** [comment]
Hi, I also an into a problem regarding these files. Could you please tell me how these files were generated or provide them directly.Thanks a lot!
